### ISSUE TITLE
按照Beetcb的方式获取refresh_token

### ISSUE THREAD

**Issue by hotmop** [SomeBottle/OdIndex#13]
这个获取方式没看懂，看cf大佬写的有点笼统，请问需要安装npm吗？不太懂，有没有更好获取这个值的办法？

**Comment by SomeBottle** [comment]
不知道你有没有看到，他有十分详细的中文部署指南
https://github.com/spencerwooo/onedrive-cf-index/blob/main/README-CN.md#%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97  
需要nodejs环境

**Comment by SomeBottle** [comment]
他们还写了详细的准备工作
https://github.com/spencerwooo/onedrive-cf-index/blob/main/README-CN.md#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

**Comment by SomeBottle** [comment]
就是不需要wrangler罢了

**Comment by hotmop** [comment]
好的 谢谢了  能不能像zfile或者onemanager那样获取值？我感觉在安装npm真的好不方便

**Comment by SomeBottle** [comment]
> 好的 谢谢了 能不能像zfile或者onemanager那样获取值？我感觉在安装npm真的好不方便

目前只能通过别的工具获取到refresh token，windows上部署npm环境就是一个安装包的事情，不麻烦的。
