### ISSUE TITLE
能不能简化下获取值的方式？

### ISSUE THREAD

**Issue by hotmop** [SomeBottle/OdIndex#14]
能不能像zfile或者onemanager那样获取值？我感觉在安装npm真的好不方便 希望作者考虑下，虽然是三个文件 光是折腾npm就挺麻烦的， 以上2个程序就是安装简单方便

**Comment by SomeBottle** [comment]
这个程序本来就是重在精简的，而没有落实在安装方便上。
这也是为什么我没有写上传文件部分。

**Comment by hotmop** [comment]
我并没说上传接口 我主要说这个值获取太麻烦，还要安装npm 有没有简便的方式获取呢

**Comment by SomeBottle** [comment]
> 我并没说上传接口 我主要说这个值获取太麻烦，还要安装npm 有没有简便的方式获取呢

简单说吧，我没有做安装向导的计划。如果你觉得npm太麻烦，我只有保留以前heymind的一个获取token的静态页  
https://github.com/SomeBottle/OdIndex/tree/master/heymind  
是否失效已很久未测试

**Comment by SomeBottle** [comment]
还有就是你在onemanager这些程序里获得的refreshtoken是可以直接拿来用的，转移很方便

**Comment by hotmop** [comment]
谢谢作者 通用的话我测试下
