### ISSUE TITLE
首页空白

### ISSUE THREAD

**Issue by littlegolden** [SomeBottle/OdIndex#16]
按照步骤填写好了 refresh_token，唯一跟教程的区别是 redirect_url 填的是 http://localhost:3000

因为 http://localhost 一直是拒绝访问，所以加了端口号，index.php 里也相应增加了 3000 端口号。

首页打开是完全空白的。控制台也没有报错

**Comment by SomeBottle** [comment]
有一点需要注意，redirect_url是用于附在发给微软api的请求里的
也就是说你在Azure Portal里配置的允许的redirect_url也要带上端口，不能仅仅只改本地

如果还是不行，再试着打开一下php.ini里的报错选项，注释掉index.php的第9行error_reporting，这样按理来说是会显示报错的。接着把报错内容贴在这里即可

关于带端口的情况我尚未测试过，不知道微软那边支不支持这样

**Comment by DieMoe233** [comment]
Azure Application可以添加多个回调URL，你可以两个都加。

**Comment by littlegolden** [comment]
> Azure Application可以添加多个回调URL，你可以两个都加。

但是没用。。。实在是懵了

**Comment by littlegolden** [comment]
> 有一点需要注意，redirect_url是用于附在发给微软api的请求里的 也就是说你在Azure Portal里配置的允许的redirect_url也要带上端口，不能仅仅只改本地
> 
> 如果还是不行，再试着打开一下php.ini里的报错选项，注释掉index.php的第9行error_reporting，这样按理来说是会显示报错的。接着把报错内容贴在这里即可
> 
> 关于带端口的情况我尚未测试过，不知道微软那边支不支持这样

好的，等下测试一下

**Comment by littlegolden** [comment]
伪静态写不写都一样：

首页报错：
```
Notice: Undefined offset: 1 in /www/wwwroot/e5.xxxx.xyz/index.php on line 463

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220

Notice: Undefined offset: 1 in /www/wwwroot/e5.xxxx.xyz/index.php on line 463

Notice: Undefined index: file in /www/wwwroot/e5.xxxx.xyz/index.php on line 365

Notice: Trying to access array offset on value of type null in /www/wwwroot/e5.xxxx.xyz/index.php on line 365

Notice: Undefined index: file in /www/wwwroot/e5.xxxx.xyz/index.php on line 365

Notice: Trying to access array offset on value of type null in /www/wwwroot/e5.xxxx.xyz/index.php on line **365**
```

进入一个目录：
```
Notice: Undefined offset: 1 in /www/wwwroot/e5.xxxx.xyz/index.php on line 463

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220

Notice: Undefined index: query in /www/wwwroot/e5.xxxx.xyz/index.php on line 220
```

**Comment by SomeBottle** [comment]
@littlegolden 测试了一会儿，我能复现出来同样错误了。你是不是没有把[```template.html```](https://github.com/SomeBottle/OdIndex/blob/master/template.html)放到相同目录下，或者这个文件是空的  

![image](https://user-images.githubusercontent.com/12976469/141302571-9c8c59c8-737c-4023-835a-2dfaaf67f9cc.png)

**Comment by SomeBottle** [comment]
没有模板文件当然是渲染不出页面的😂

**Comment by littlegolden** [comment]
> 没有模板文件当然是渲染不出页面的😂

在一个页面的，首页有页面，但是目录没有，e5.itnt.xyz

**Comment by SomeBottle** [comment]
有没有开缓存
![image](https://user-images.githubusercontent.com/12976469/141303438-2cc3fa83-99ca-49d6-9f99-c267954015c6.png)
可能你之前空白页被文件缓存了
你可以手动删除文件缓存，默认是```./data/cache```目录

**Comment by littlegolden** [comment]
我应该没开缓存，配置就仓库默认的没有动。cache目录是空的
![image](https://user-images.githubusercontent.com/35162802/141304346-97754862-3f53-4be2-8a48-2a815042095e.png)

**Comment by SomeBottle** [comment]
确实不是模板问题
奇了怪了，也没看到请求上的错误，报错也都是notice级别

**Comment by SomeBottle** [comment]
说一下PHP版本吧，然后检查一下有没有openssl扩展
我看到主要返回的是Not Found，也就是代表后端请求返回为空。之前遇到过这个问题，可能openssl扩展的原因
启用或者禁用openssl扩展试一下。

**Comment by littlegolden** [comment]
> 说一下PHP版本吧，然后检查一下有没有openssl扩展 我看到主要返回的是Not Found，也就是代表后端请求返回为空。之前遇到过这个问题，可能openssl扩展的原因 启用或者禁用openssl扩展试一下。

这么重要的事情给忘了，刚刚用的 PHP 74，换了 8.0 也有这个问题。楼主需要服务器权限看看吗

**Comment by SomeBottle** [comment]
> 这么重要的事情给忘了，刚刚用的 PHP 74，换了 8.0 也有这个问题。楼主需要服务器权限看看吗    

我又复现出了同样的情况，原因是：  

在**网站服务器设置了伪静态**的同时**在index.php中配置了```'rewrite'=>false```**    

刚刚看了一下你的站点，有可能是这个问题了

你可以在index.php相关配置改成```'rewrite'=>true```试试
亦可以暂时撤去网站服务器的伪静态设置

**Comment by SomeBottle** [comment]
还是不行的话，我可以去层主的服务器上调试检查一下，隐私信息可以通过邮件发给我😂
邮箱就是我的Github账户邮箱

**Comment by SomeBottle** [comment]
问题解决： 
1. 要展示onedrive**根目录**内容时要设置```base => ''``` (这里是我默认配置写错了，很抱歉(ノへ￣、)  
2. 340行左右判断空目录用的是```isset```，已改为```array_key_exists```方法  

感谢各位的协助排查！

**Comment by littlegolden** [comment]
大赞！辛苦了
