### ISSUE TITLE
怎么实现url不加“/”也能访问目录列表

### ISSUE THREAD

**Issue by HCARX** [SomeBottle/OdIndex#17]
怎么实现url不加“/”也能访问目录列表，谢谢

**Comment by SomeBottle** [comment]
我刚刚提交了一次更新，现在你在访问 
```https://xxx/Documents ```这种末尾不带/的url时会给你自动重定向到 ```https://xxx/Documents/ ```  

如果是需要访问```https://xxx/Documents ```来渲染目录，我只能很遗憾的说没有支持的计划，因为这样很有可能导致多处路径问题。

**Comment by HCARX** [comment]
> 我刚刚提交了一次更新，现在你在访问 `https://xxx/Documents `这种末尾不带/的url时会给你自动重定向到 `https://xxx/Documents/ `
> 
> 如果是需要访问`https://xxx/Documents `来渲染目录，我只能很遗憾的说没有支持的计划，因为这样很有可能导致多处路径问题。

非常感谢！

**Comment by SomeBottle** [comment]
感谢反馈，这也是个比较久的遗留问题了，解决了就好（づ￣3￣）

**Comment by HCARX** [comment]
您好，未完全解决问题。
访问
https://od.xbottle.top/Videos/Abroad/
会被重定向到
https://od.xbottle.top/Videos/Videos/Abroad/

出现两个Videos

**Comment by SomeBottle** [comment]
所以说动路径这方面确实很容易出问题😂，现在已经解决了。

https://github.com/SomeBottle/OdIndex/releases/tag/4.5
