### ISSUE TITLE
想问一下关于伪静态开启的问题

### ISSUE THREAD

**Issue by zxfccmm4** [SomeBottle/OdIndex#19]
你好，
我根据步骤在宝塔面板开启了伪静态，但是我点击页面上的分类网址中间还是自动回添加上 ？
请问是否是我没有成功。
谢谢解答。
我的地址  https://od.steveee.top

**Comment by SomeBottle** [comment]
光网站服务器开启伪静态还不够，你还需要对配置文件进行修改：  
https://github.com/SomeBottle/OdIndex#config  

```'rewrite'=>true,```

**Comment by zxfccmm4** [comment]
> 光网站服务器开启伪静态还不够，你还需要对配置文件进行修改： https://github.com/SomeBottle/OdIndex#config
> 
> `'rewrite'=>true,`

ok 谢谢回复  已经成功。
再次感谢。
