### ISSUE TITLE
There is no password protect

### ISSUE THREAD

**Issue by ashish453** [SomeBottle/OdIndex#3]
In Heymind version we can inout user name and password for our index site but in your php script i can't find any:(
please add this feature

**Comment by SomeBottle** [comment]
![image](https://user-images.githubusercontent.com/12976469/85229121-9dee2200-b41a-11ea-91e1-e906acb5fa4d.png)

Oh buddy, I have added the feature of protecting directory by password before, but what makes it different is that you need to convert your password to **lowercase 32-bit md5** and write it in a .password file which is put under the directory you're willing to protect.

**Comment by SomeBottle** [comment]
Limited by the api's frequency limitation , the password is only able to protect the directory from being listed.If someone knows the filepath under the directory , the password protection will no longer be useful.

**Comment by ashish453** [comment]
@SomeBottle  I think adding .password file  will only work on directory level !!
and if someone will will share the file link then there is no work of password inside .password

Correct me if i am wrong!

opps i find your comment late !!

**Comment by SomeBottle** [comment]
Oh, I haven't test the password protection for the index page , if the **.password** file under the index directory doesn't work , I'll check it out later.

Thanks for your feedback , if there's any problem , I'll try to fix it a month later due to my preparing entrance exam of college .

**Comment by ashish453** [comment]
Ok :)

**Comment by SomeBottle** [comment]
![QQ截图20200625145715](https://user-images.githubusercontent.com/12976469/85673035-10e6e980-b6f6-11ea-97eb-bc61ef89d980.png)
![QQ图片20200625145807](https://user-images.githubusercontent.com/12976469/85673049-13e1da00-b6f6-11ea-97bf-aaee064bc26e.png)

Hey bro, I just tested the .password file under the index directory and found that it actually worked.
Have you ever tried that?

**Comment by ashish453** [comment]
Oh yess.

**Comment by ashish453** [comment]
By the way bro please do something about multiple accounts support. 
Index multiple accounts
