### ISSUE TITLE
显示 Failed to get accesstoken. Maybe refresh_token expired

### ISSUE THREAD

**Issue by ziyou2** [SomeBottle/OdIndex#4]
显示 Failed to get accesstoken. Maybe refresh_token expired
目录下并没有生成token.php
请问具体该如何处理呢?

**Comment by SomeBottle** [comment]
久等了
https://github.com/SomeBottle/OdIndex#notice  
README内有写

**Comment by SomeBottle** [comment]
如果没有生成token.php就是权限不够，要检查index.php的读写权限

**Comment by cbr252522489** [comment]
https://heymind.github.io/tools/microsoft-graph-api-auth

**Comment by SomeBottle** [comment]
> https://heymind.github.io/tools/microsoft-graph-api-auth

大陆部分地区github.io因运营商影响被解析到127.0.0.1，请用科学上网工具

**Comment by ziyou2** [comment]
> 如果没有生成token.php就是权限不够，要检查index.php的读写权限

index.php我改成了777的权限，还是一样，还需要修改什么？

**Comment by SomeBottle** [comment]
refreshtoken正常配置了吗，还有就是你的账户是什么类型
