### ISSUE TITLE
很尴尬，浏览器直接响应500，有办法找到是什么问题吗？

### ISSUE THREAD

**Issue by alxcer** [SomeBottle/OdIndex#5]

**Comment by alxcer** [comment]
之前有用过别的类似oneindex的

**Comment by SomeBottle** [comment]
确认配置无误吗

**Comment by alxcer** [comment]
> 确认配置无误吗

在代码中把refresh_token、client_id、client_secret改为自己的，应该没错的

**Comment by SomeBottle** [comment]
![image](https://user-images.githubusercontent.com/12976469/93781552-12c03a80-fc5c-11ea-9c3d-2dd9c3a0a774.png)
把这行注释掉后打开PHP报错

**Comment by alxcer** [comment]
> 确认配置无误吗

好了，是忘了设置文件夹权限为777了，感谢大佬。另外问一下，怎么上传文件呢？😂

**Comment by SomeBottle** [comment]
OdIndex这个程序没有做上传文件功能的打算😂  
如果造成不便敬请谅解

**Comment by alxcer** [comment]
> OdIndex这个程序没有做上传文件功能的打算😂
> 如果造成不便敬请谅解

哦哦。好的 谢谢😂
