### ISSUE TITLE
好像是不支持世纪互联哈？

### ISSUE THREAD

**Issue by wangjiale1125** [SomeBottle/OdIndex#6]
好像是不支持世纪互联哈？

**Comment by SomeBottle** [comment]
只支持od国际版，带来不便很抱歉

**Comment by SomeBottle** [comment]
其实是咱还没有用过世纪互联版的，没办法做测试😂。之后我订阅世纪互联版后会增加相关的api

**Comment by wangjiale1125** [comment]
是否有想法移植一个支持世纪互联的版本呢？

**Comment by wangjiale1125** [comment]
https://github.com/spencerwooo/onedrive-cf-index  这个已经支持世纪互联了，感觉界面挺好看的，但是只能部署在CF访问还是有点点慢

**Comment by wangjiale1125** [comment]
我可以协助测试

**Comment by SomeBottle** [comment]
我之后有时间就整上吧，大学这边课表排的有点满😂

**Comment by SomeBottle** [comment]
你好，我刚刚做了一点小更新，还没测试是否支持世纪互联，希望你能帮忙看一下：  
https://github.com/SomeBottle/OdIndex/blob/master/README.md#%E4%B8%96%E7%BA%AA%E4%BA%92%E8%81%94%E6%B5%8B%E8%AF%95

**Comment by wangjiale1125** [comment]
好的，明天我测试一下

**Comment by wangjiale1125** [comment]
> 你好，我刚刚做了一点一点更新，还没测试是否支持世纪互联，希望你能帮忙看一下：[https](https://github.com/SomeBottle/OdIndex/blob/master/README.md#%E4%B8%96%E7%BA%AA%E4%BA%92%E8%81%94%E6%B5%8B%E8%AF%95) :
> [//github.com/SomeBottle/OdIndex/blob/master/README.md#%E4%B8 ％96％E7％BA％AA％E4％BA％92％E8％81％94％E6％B5％8B％E8％AF％95](https://github.com/SomeBottle/OdIndex/blob/master/README.md#%E4%B8%96%E7%BA%AA%E4%BA%92%E8%81%94%E6%B5%8B%E8%AF%95)

可以使用了，但是我的php的拓展有点问题，我重新弄一下，稍后给demo

**Comment by wangjiale1125** [comment]
> 你好，我刚刚做了一点小更新，还没测试是否支持世纪互联，希望你能帮忙看一下：
> https://github.com/SomeBottle/OdIndex/blob/master/README.md#%E4%B8%96%E7%BA%AA%E4%BA%92%E8%81%94%E6%B5%8B%E8%AF%95

https://www.2kaixin.com/
可以了，但是还有个问题，就是base的路径好像不能设置中文，只能是英文，另外就是伪静态配置好了，但是访问的之后还是会有/?/这种

**Comment by SomeBottle** [comment]
base路径如果是中文的话可能要过一道url转义  
?/这个的话，如果配置了伪静态就可以修改头部的rewrite设置为true
![BME4Z{F%IZ@RWW7@ 4ROW1H](https://user-images.githubusercontent.com/12976469/96261030-6d964900-0ff2-11eb-9156-17a2be545d14.png)

**Comment by SomeBottle** [comment]
我稍后研究一下base的设置，后面可能还会给文件列表加上翻页的功能，全部列出来体验不太行

**Comment by wangjiale1125** [comment]
> base路径如果是中文的话可能要过一道url转义
> ?/这个的话，如果配置了伪静态就可以修改头部的rewrite设置为true
> ![BME4Z{F%IZ@RWW7@ 4ROW1H](https://user-images.githubusercontent.com/12976469/96261030-6d964900-0ff2-11eb-9156-17a2be545d14.png)

好的，多谢，主题风格能否改成https://github.com/spencerwooo/onedrive-cf-index这个项目的那种？

**Comment by SomeBottle** [comment]
主题这个我准备自己有时间就改一下，照搬不是很好的感觉

**Comment by wangjiale1125** [comment]
> 主题这个我准备自己有时间就改一下，照搬不是很好的感觉

主要还是觉得那个好看，等哪天工作不忙的时候我看一下，多谢大佬，如果还需要测试，滴滴我就行

**Comment by SomeBottle** [comment]
OdIndex 2.0已经放出，这回自己整了个模板
