### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Micraow** [SomeBottle/OdIndex#8]
首先我想说这真的是一个很好的项目。
但是尚有可改进之处。

首先就是我认为原版的那个主题太过于单调了。而且看起来也不是很美观。我试过了很多的oneindex ,发现spencerwooo的[项目](https://github.com/spencerwooo/onedrive-cf-index) 
看起来很好看，希望作者能够使用它的CSS。

其次就是虽然实现了一些基本的文件预览功能。但是大部分的文件还是不能预览。建议参考
[https://github.com/jialezi/oneindex-j](https://github.com/jialezi/oneindex-j) 
可以实现docx pptx 等文件的预览,而且不消耗服务器的流量。将这个预览方式的文件类型支持列表中添加.zip .rar  等,便可以实现通过Onedrive 的文件预览

[参考官方文档。](https://docs.microsoft.com/zh-cn/graph/api/driveitem-preview?view=graph-rest-1.0)
 
希望采纳，我很需要这些功能。

**Comment by SomeBottle** [comment]
感谢提出建议，不过我现在有点忙于学业，稍后放假了我会考虑一下的~

**Comment by SomeBottle** [comment]
相关预览功能已经准备的差不多了，稍后会放出OdIndex2.0，感谢你的建议！
