### ISSUE TITLE
又一些建议

### ISSUE THREAD

**Issue by Micraow** [SomeBottle/OdIndex#9]
1. 图床功能

https://github.com/jialezi/oneindex-j
参见

但这个有点问题，有时不能成功上传，且路径太长，上传后路径类似

image/2020/12/06/aaa.jpg

2.可恢复的上传，

即大文件切片上传

可参见官方文档

3.离线下载

**Comment by SomeBottle** [comment]
你好，这个项目本来没有规划上传和离线下载适配功能的，项目结构不适合搞这么复杂的。
